#!/usr/bin/env bash
#
# One-time server provisioning for the Gymdog commerce platform.
# Target: fresh Ubuntu 24.04 LTS. Run as root. Idempotent — safe to re-run.
#
#   scp deploy/provision.sh root@SERVER:/root/ && ssh root@SERVER 'bash /root/provision.sh'
#
# Installs the LEMP stack (nginx + PHP 8.4-FPM + MySQL 8 + Redis), a dedicated
# app user with its own PHP-FPM pool, a swap file, and a firewall. It does NOT
# deploy the app — see deploy/PROVISIONING.md for the ordered runbook.
#
set -euo pipefail

APP_USER="gymdog"
APP_DIR="/home/${APP_USER}/app"
DB_NAME="gymdog"
DB_USER="gymdog"
PHP="php8.4"
CRED_FILE="/home/${APP_USER}/server-credentials.txt"

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_MODE=a          # auto-restart services, no interactive prompt
export NEEDRESTART_SUSPEND=1

echo "==> System packages"
apt-get update -y
apt-get upgrade -y
apt-get install -y software-properties-common curl git unzip acl ufw fail2ban

echo "==> PHP 8.4 (ondrej/php)"
add-apt-repository -y ppa:ondrej/php
apt-get update -y
apt-get install -y \
  ${PHP}-fpm ${PHP}-cli ${PHP}-mysql ${PHP}-redis ${PHP}-mbstring \
  ${PHP}-xml ${PHP}-curl ${PHP}-zip ${PHP}-gd ${PHP}-bcmath \
  ${PHP}-intl ${PHP}-imagick ${PHP}-gmp

echo "==> nginx, MySQL, Redis"
apt-get install -y nginx mysql-server redis-server

echo "==> Composer"
if ! command -v composer >/dev/null; then
  curl -fsSL https://getcomposer.org/installer -o /tmp/composer-setup.php
  php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
  rm -f /tmp/composer-setup.php
fi

echo "==> Swap (2G) — headroom for composer/MySQL on a 4G box"
if ! swapon --show | grep -q /swapfile; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

echo "==> App user: ${APP_USER}"
if ! id "${APP_USER}" >/dev/null 2>&1; then
  adduser --disabled-password --gecos "" "${APP_USER}"
fi
# Give the app user the same SSH key as root so deploys can log in as ${APP_USER}.
install -d -m 700 -o "${APP_USER}" -g "${APP_USER}" "/home/${APP_USER}/.ssh"
if [ -f /root/.ssh/authorized_keys ]; then
  cp /root/.ssh/authorized_keys "/home/${APP_USER}/.ssh/authorized_keys"
  chown "${APP_USER}:${APP_USER}" "/home/${APP_USER}/.ssh/authorized_keys"
  chmod 600 "/home/${APP_USER}/.ssh/authorized_keys"
fi
install -d -o "${APP_USER}" -g "${APP_USER}" "${APP_DIR}"

echo "==> Dedicated PHP-FPM pool for ${APP_USER}"
POOL="/etc/php/8.4/fpm/pool.d/${APP_USER}.conf"
cat > "${POOL}" <<POOLCONF
[${APP_USER}]
user = ${APP_USER}
group = ${APP_USER}
listen = /run/php/${APP_USER}.sock
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 12
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 4
php_admin_value[upload_max_filesize] = 20M
php_admin_value[post_max_size] = 20M
POOLCONF
# Remove the default www pool so only the app pool runs.
rm -f /etc/php/8.4/fpm/pool.d/www.conf
systemctl restart ${PHP}-fpm

echo "==> MySQL database + app user"
DB_PASS="$(openssl rand -base64 24 | tr -d '/+=' | cut -c1-24)"
mysql <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
ALTER USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PASS}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

echo "==> Firewall (SSH + HTTP + HTTPS)"
ufw allow OpenSSH
ufw allow 'Nginx Full'
ufw --force enable

echo "==> Saving credentials to ${CRED_FILE}"
cat > "${CRED_FILE}" <<CREDS
# Generated by provision.sh — used to build the app .env
DB_DATABASE=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASS}
APP_DIR=${APP_DIR}
PHP_FPM_SOCK=/run/php/${APP_USER}.sock
CREDS
chown "${APP_USER}:${APP_USER}" "${CRED_FILE}"
chmod 600 "${CRED_FILE}"

echo
echo "✅ Provisioning complete."
echo "   App user : ${APP_USER}   App dir: ${APP_DIR}"
echo "   DB creds : ${CRED_FILE} (readable by ${APP_USER})"
echo "   Next     : follow deploy/PROVISIONING.md (deploy key → clone → .env → SSL)."
